### ISSUE TITLE
Calculate execution time on the backend

### ISSUE THREAD

**Issue by IvanBila** [JefferMarcelino/sml-frontend#11]
### Summary

Hey I noticed that the execution time is being calculated on the front-end, I think we might be getting inacurate measures, for the current implementation also includes the time the data travels over the wire, response deserialization, moreover the `performance.now()` is not [reliable on the front-end](https://caniuse.com/?search=performance.now()):

>1. The timestamp is not actually high-resolution. To mitigate security threats such as Spectre, browsers currently round the result to varying degrees.

>2. In Firefox 55-57, the privacy.resistFingerprinting preference can be enabled to change the precision to 100ms.

https://github.com/JefferMarcelino/sml-frontend/blob/8b90732fee12e24056e6ee307cac38fe9f2a837c/src/Components/Editor/index.tsx#L33-L35

**Comment by JefferMarcelino** [comment]
Hi @IvanBila let me make some corrections on the backend and then I will merge what you have done. Because the main branch of [sml-playground](https://github.com/JefferMarcelino/sml-playground) currently does not return the execution time.

**Comment by JefferMarcelino** [comment]
And one more time, thank you for contributing, I am really learning a lot of interesting things ❤️
